import turtle
import time
turtle .screensize(500,600)
turtle.pensize(3)
turtle.speed(10)
#头
turtle.begin_fill()
turtle.color("black","#00a0de")
turtle.circle(140)
turtle.end_fill()


turtle.color("black","white")
turtle.begin_fill()
turtle.circle(110)
turtle.end_fill()

#鼻子
turtle.penup()
turtle.goto(0,150)
turtle.pendown()
turtle.color("black","red")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.goto(10,170)
turtle.pendown()
turtle.color("white","white")
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()
#眼睛
turtle.penup()
turtle.goto(-30,180)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.penup()
turtle.goto(30,180)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.penup()
turtle.goto(20,200)
turtle.pendown()
turtle.color("black","black")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()

turtle.penup()
turtle.goto(-20,200)
turtle.pendown()
turtle.color("black","black")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()

turtle.penup()
turtle.goto(-20,210)
turtle.pendown()
turtle.color("white","white")
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()

turtle.penup()
turtle.goto(20,210)
turtle.pendown()
turtle.color("white","white")
turtle.begin_fill()
turtle.circle(3)
turtle.end_fill()

#胡子
turtle.penup()
turtle.goto(0,150)
turtle.pendown()
turtle.color("black")
turtle.right(90)
turtle.forward(90)

turtle.penup()
turtle.goto(-20,130)
turtle.pendown()
turtle.color("black")
turtle.right(100)
turtle.forward(60)

turtle.penup()
turtle.goto(-20,110)
turtle.pendown()
turtle.color("black")
turtle.left(10)
turtle.forward(60)

turtle.penup()
turtle.goto(-20,90)
turtle.pendown()
turtle.color("black")
turtle.left(10)
turtle.forward(60)

turtle.penup()
turtle.goto(20,130)
turtle.pendown()
turtle.color("black")
turtle.right(180)
turtle.forward(60)

turtle.penup()
turtle.goto(20,110)
turtle.pendown()
turtle.color("black")
turtle.right(10)
turtle.forward(60)

turtle.penup()
turtle.goto(20,90)
turtle.pendown()
turtle.color("black")
turtle.right(10)
turtle.forward(60)

#嘴巴
turtle.penup()
turtle.goto(-70,70)
turtle.pendown()
turtle.pencolor("black")
turtle.right(17)
turtle.circle(150,55)

#红绳
turtle.penup()
turtle.goto(-80,20)
turtle.pendown()
turtle.pensize(15)
turtle.color("red")
turtle.right(60)
turtle.circle(150,65)
#铃铛
turtle.penup()
turtle.goto(-20,-40)
turtle.pendown()
turtle.pensize(2)
turtle.color("black","orange")
turtle.begin_fill()
turtle.right(90)
turtle.circle(25)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-30)
turtle.pendown()
turtle.pensize(2)
turtle.color("black","gray")
turtle.begin_fill()
turtle.right(90)
turtle.circle(5)
turtle.end_fill()

turtle.penup()
turtle.goto(5,-40)
turtle.pendown()
turtle.pensize(2)
turtle.color("black")
turtle.left(10)
turtle.circle(20,40)

#身体
turtle.color("black","#00a0de")
turtle.begin_fill()
turtle.penup()
turtle.goto(80,20)
turtle.pendown()
turtle.left(118)
turtle.forward(120)
turtle.right(90)
turtle.forward(45)
turtle.right(90)
turtle.goto(110,-30)



turtle.penup()
turtle.goto(110,-25)
turtle.pendown()
turtle.left(70)
turtle.forward(220)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.circle(35,180)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(205)
turtle.left(110)
turtle.forward(75)
turtle.right(90)
turtle.forward(45)
turtle.right(90)
turtle.forward(130)
turtle.end_fill()

turtle.color("black","white")
turtle.begin_fill()
turtle.penup()
turtle.goto(-62,5)
turtle.pendown()
turtle.right(163)
turtle.circle(95,285)
turtle.end_fill()


#红绳
turtle.penup()
turtle.goto(-80,23)
turtle.pendown()
turtle.pensize(15)
turtle.color("red")
turtle.right(-183)
turtle.circle(150,65)
#铃铛
turtle.penup()
turtle.goto(10,-40)
turtle.pendown()
turtle.pensize(2)
turtle.color("black","orange")
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()

turtle.penup()
turtle.goto(0,-35)
turtle.pendown()
turtle.pensize(2)
turtle.color("black","gray")
turtle.begin_fill()
turtle.circle(5)
turtle.end_fill()
turtle.right(160)
turtle.color("black")
turtle.circle(20,30)
#手掌
turtle.penup()
turtle.goto(183,52)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()

turtle.penup()
turtle.goto(-245,-50)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(30)
turtle.end_fill()
#口袋
turtle.penup()
turtle.goto(-72,-77)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.right(-9)
turtle.circle(70,180)
turtle.left(90)
turtle.forward(140)
turtle.end_fill()
#脚
turtle.penup()
turtle.goto(-117,-245)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(20,180)
turtle.forward(82)
turtle.circle(20,180)
turtle.end_fill()

turtle.penup()
turtle.goto(32,-245)
turtle.pendown()
turtle.color("black","white")
turtle.begin_fill()
turtle.circle(20,180)
turtle.forward(82)
turtle.circle(20,180)
turtle.end_fill()

turtle.penup()
turtle.goto(250,200)
turtle.pensize(10)
turtle.write("李文达")

time.sleep(50)